# Generated by Django 3.2.17 on 2023-04-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartTraffic', '0003_fine_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='number_img',
            field=models.ImageField(blank=True, upload_to='num_pics'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='surname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle',
            field=models.CharField(blank=True, choices=[('car', 'car'), ('bus', 'bus'), ('truck', 'truck')], max_length=10),
        ),
    ]
