# Generated by Django 3.2.17 on 2023-04-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartTraffic', '0004_auto_20230416_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='accident_img',
            field=models.ImageField(blank=True, upload_to='num_pics'),
        ),
    ]
