# Generated by Django 3.2.17 on 2023-04-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartTraffic', '0006_fine_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='number_img',
            field=models.ImageField(blank=True, upload_to='num_pics'),
        ),
    ]
