# Generated by Django 3.2.18 on 2023-04-16 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartTraffic', '0007_fine_number_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartTraffic.driver'),
        ),
    ]
